### ISSUE TITLE
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Exception opening port "8082" (port may be in use), cause: "java.net.BindException

### ISSUE THREAD

**Issue by biswagitrepo** [biswagitrepo/MuleCustomerApps#1]
Exception opening port "8082" (port may be in use) H2DB
The Web Console server could not be started. Possible cause: another server is already running at http://192.168.56.1:8082
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Exception opening port "8082" (port may be in use), cause: "java.net.BindException: Address already in use: JVM_Bind" [90061-195]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:200)
        at org.h2.util.NetUtils.createServerSocket(NetUtils.java:166)
        at org.h2.server.web.WebServer.start(WebServer.java:342)
        at org.h2.tools.Server.start(Server.java:484)
        at org.h2.tools.Server.runTool(Server.java:323)
        at org.h2.tools.Server.main(Server.java:118)
Caused by: java.net.BindException: Address already in use: JVM_Bind
        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.net.PlainSocketImpl.bind(Unknown Source)
        at java.net.ServerSocket.bind(Unknown Source)
        at java.net.ServerSocket.<init>(Unknown Source)
        at java.net.ServerSocket.<init>(Unknown Source)
        at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:196)
        ... 5 more

**Comment by biswagitrepo** [comment]
I found two ways to fix this issue considering you are running the H2DB in a Windows environment:

Open Command Prompt in Administrator mode to find out the processes running on the port no: 8082
    1. Goto cmd prompt 
     2. Type netstat -a -n -o | findstr 8082
    Gives the below output
    TCP 0.0.0.0:8082 0.0.0.0.0 LISTENING 2895(PID)
    TCP [::]:8082 [::]:0 LISTENING 2885(PID)
   3. Run this command to kill the process 
      TASKKILL /F /PID 2885

If you have anti-virus running on your system or don't have admin rights to kill the PID you can try the below method:
In cmd prompt Run the below command  to create .h2.server.properties in C:\Users\UserName directory

> java -jar h2-1.4.196.jar -tcp -tcpPort 8083 

Go to your C:\Documents and Settings\Username or C:\Users\UserName
Locate the .h2.server.properties and change the default webPort=8082 to webPort=8084 or some port no not being used.

Now you can start the H2DB.

**Comment by biswagitrepo** [comment]
![h2db_capture](https://user-images.githubusercontent.com/31786238/30842031-f34b2dc2-a2db-11e7-8ad9-2be7dbec03a8.PNG)
